### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by brunoimbrizi** [dmnsgn/async-preloader#2]
Building a project with `async-preloader@3.3.0` yielded the following parse error:
```
C:\Users\bruno\Documents\jobs\2018\thirty-three\ee-careers\node_modules\lodash-es\get.js:1
import baseGet from './_baseGet.js';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```
Reverting to the previous version I had installed `async-preloader@3.0.1` made the error disappear.

Just a quick issue report, I haven't had the time to investigate it any further.

**Comment by dmnsgn** [comment]
I pushed some changes recently indeed.
I am guessing you have a build system that transform ES6 modules into ES5 (Babel?) and in the configuration you have something like `exclude: /(node_modules)/,` preventing `node_modules` packages from being transformed.

You might want to let `lodash-es` be still transformed eg:
`exclude: /node_modules\/(?!(lodash-es|another-module-that-need-es6to5-transformed)\/).*/,`

But to be honest I should probably drop the dependency entirely.

**Comment by dmnsgn** [comment]
`lodash-es` has been removed in v4.0.1 but you might still need to exclude `fontfaceobserver-es`

**Comment by dmnsgn** [comment]
Closing as:

- bundlers should pick up the right key in `fontfaceobserver-es` package.json: https://github.com/dmnsgn/fontfaceobserver/blob/6c12e94a086c011f1e1447e79031c3de6ee5ec2a/package.json#L16-L19
- version [5.0.x](https://github.com/dmnsgn/async-preloader/releases/tag/v5.0.2) is now declaring this module as type module
